<?php
/**
 * BillingDocumentItemApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  BeLenka\SAP\BillingDocumentRCG2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Billing Document - Read, Cancel, GetPDF
 *
 * Consumers of this inbound service can read and cancel billing documents inside your system by sending OData requests. In addition, they can request entire billing documents in PDF format. The service makes billing document data available through its header, item, business partner, and pricing element entities.
 *
 * The version of the OpenAPI document: 1.1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace BeLenka\SAP\BillingDocumentRCG2\Test\Api;

use \BeLenka\SAP\BillingDocumentRCG2\Configuration;
use \BeLenka\SAP\BillingDocumentRCG2\ApiException;
use \BeLenka\SAP\BillingDocumentRCG2\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * BillingDocumentItemApiTest Class Doc Comment
 *
 * @category Class
 * @package  BeLenka\SAP\BillingDocumentRCG2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BillingDocumentItemApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for aBillingDocumentBillingDocumentToItemGet
     *
     * Reads all items of a specific billing document..
     *
     */
    public function testABillingDocumentBillingDocumentToItemGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aBillingDocumentItemBillingDocumentBillingDocumentBillingDocumentItemBillingDocumentItemGet
     *
     * Reads a specific billing document item..
     *
     */
    public function testABillingDocumentItemBillingDocumentBillingDocumentBillingDocumentItemBillingDocumentItemGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aBillingDocumentItemBillingDocumentBillingDocumentBillingDocumentItemBillingDocumentItemToBillingDocumentGet
     *
     * Reads the billing document header for a specific item..
     *
     */
    public function testABillingDocumentItemBillingDocumentBillingDocumentBillingDocumentItemBillingDocumentItemToBillingDocumentGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aBillingDocumentItemBillingDocumentBillingDocumentBillingDocumentItemBillingDocumentItemToItemTextGet
     *
     * Reads the item texts of a specific billing document..
     *
     */
    public function testABillingDocumentItemBillingDocumentBillingDocumentBillingDocumentItemBillingDocumentItemToItemTextGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aBillingDocumentItemBillingDocumentBillingDocumentBillingDocumentItemBillingDocumentItemToPartnerGet
     *
     * Reads the item business partners of a specific billing document item..
     *
     */
    public function testABillingDocumentItemBillingDocumentBillingDocumentBillingDocumentItemBillingDocumentItemToPartnerGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aBillingDocumentItemBillingDocumentBillingDocumentBillingDocumentItemBillingDocumentItemToPricingElementGet
     *
     * Reads the item pricing elements of a specific billing document item..
     *
     */
    public function testABillingDocumentItemBillingDocumentBillingDocumentBillingDocumentItemBillingDocumentItemToPricingElementGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aBillingDocumentItemGet
     *
     * Reads all billing document Items..
     *
     */
    public function testABillingDocumentItemGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aBillingDocumentItemPartnerBillingDocumentBillingDocumentBillingDocumentItemBillingDocumentItemPartnerFunctionPartnerFunctionToBillingDocumentItemGet
     *
     * Reads a billing document item for a specific item partner function..
     *
     */
    public function testABillingDocumentItemPartnerBillingDocumentBillingDocumentBillingDocumentItemBillingDocumentItemPartnerFunctionPartnerFunctionToBillingDocumentItemGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aBillingDocumentItemPrcgElmntBillingDocumentBillingDocumentBillingDocumentItemBillingDocumentItemPricingProcedureStepPricingProcedureStepPricingProcedureCounterPricingProcedureCounterToBillingDocumentItemGet
     *
     * Reads a billing document item for a specific item and item-level pricing element..
     *
     */
    public function testABillingDocumentItemPrcgElmntBillingDocumentBillingDocumentBillingDocumentItemBillingDocumentItemPricingProcedureStepPricingProcedureStepPricingProcedureCounterPricingProcedureCounterToBillingDocumentItemGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
