<?php
/**
 * HeaderPricingElementApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  BeLenka\SAP\BillingDocumentRCG2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Billing Document - Read, Cancel, GetPDF
 *
 * Consumers of this inbound service can read and cancel billing documents inside your system by sending OData requests. In addition, they can request entire billing documents in PDF format. The service makes billing document data available through its header, item, business partner, and pricing element entities.
 *
 * The version of the OpenAPI document: 1.1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace BeLenka\SAP\BillingDocumentRCG2\Test\Api;

use \BeLenka\SAP\BillingDocumentRCG2\Configuration;
use \BeLenka\SAP\BillingDocumentRCG2\ApiException;
use \BeLenka\SAP\BillingDocumentRCG2\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * HeaderPricingElementApiTest Class Doc Comment
 *
 * @category Class
 * @package  BeLenka\SAP\BillingDocumentRCG2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class HeaderPricingElementApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for aBillingDocumentBillingDocumentToPricingElementGet
     *
     * Reads the header pricing elements of a specific billing document..
     *
     */
    public function testABillingDocumentBillingDocumentToPricingElementGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aBillingDocumentPrcgElmntBillingDocumentBillingDocumentPricingProcedureStepPricingProcedureStepPricingProcedureCounterPricingProcedureCounterGet
     *
     * Reads the header pricing elements of a specific billing document and specific pricing element..
     *
     */
    public function testABillingDocumentPrcgElmntBillingDocumentBillingDocumentPricingProcedureStepPricingProcedureStepPricingProcedureCounterPricingProcedureCounterGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aBillingDocumentPrcgElmntBillingDocumentBillingDocumentPricingProcedureStepPricingProcedureStepPricingProcedureCounterPricingProcedureCounterToBillingDocumentGet
     *
     * Reads the billing document header for a specific header pricing element..
     *
     */
    public function testABillingDocumentPrcgElmntBillingDocumentBillingDocumentPricingProcedureStepPricingProcedureStepPricingProcedureCounterPricingProcedureCounterToBillingDocumentGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aBillingDocumentPrcgElmntGet
     *
     * Reads header pricing elements of all billing documents..
     *
     */
    public function testABillingDocumentPrcgElmntGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
