<?php
/**
 * HeaderTextApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  BeLenka\SAP\BillingDocumentRCG2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Billing Document - Read, Cancel, GetPDF
 *
 * Consumers of this inbound service can read and cancel billing documents inside your system by sending OData requests. In addition, they can request entire billing documents in PDF format. The service makes billing document data available through its header, item, business partner, and pricing element entities.
 *
 * The version of the OpenAPI document: 1.1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace BeLenka\SAP\BillingDocumentRCG2\Test\Api;

use \BeLenka\SAP\BillingDocumentRCG2\Configuration;
use \BeLenka\SAP\BillingDocumentRCG2\ApiException;
use \BeLenka\SAP\BillingDocumentRCG2\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * HeaderTextApiTest Class Doc Comment
 *
 * @category Class
 * @package  BeLenka\SAP\BillingDocumentRCG2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class HeaderTextApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for aBillingDocumentBillingDocumentToTextGet
     *
     * Reads the header texts of a specific billing document..
     *
     */
    public function testABillingDocumentBillingDocumentToTextGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aBillingDocumentTextBillingDocumentBillingDocumentLanguageLanguageLongTextIDLongTextIDGet
     *
     * Reads the header texts of a specific billing document for a specific language and long text ID..
     *
     */
    public function testABillingDocumentTextBillingDocumentBillingDocumentLanguageLanguageLongTextIDLongTextIDGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aBillingDocumentTextGet
     *
     * Reads the header texts of all billing documents..
     *
     */
    public function testABillingDocumentTextGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
